name: Github Environment

on:
    workflow_dispatch:

jobs:
    deployment:
        runs-on: ubuntu-latest

        environment:
            name: prod
            url: https://github.com

        steps:
          - name: "Print secret from environment"
          run: |
            echo "APP_SEC ${{secrets.APP_SEC }}"