name: "Default environment variables"

on:
    push:

jobs:
    mainjob:
        name: "Print the default github vars"
        runs-on: ubuntu-latest

        steps:
        - name: print-values-of-env vars
          run: |
            echo "$GITHUB_ACTION"
            echo "$GITHUB_ENV"
            echo "my top secret ${{secrets.MY_SECRET}}"
            echo "my top secret ${{secrets.MY_SECRET_NOT}}"